<h1 align = 'center'> Dataset_4

In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
import matplotlib.pyplot as plt
%matplotlib inline 
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.metrics import confusion_matrix, zero_one_loss
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
#Reading the dataset csv file as Pandas DataFrame
d = pd.read_csv("dataset_4.csv", encoding = 'utf-8')
d

Title  \
0                            Geophysical deep learning   
1               Deep learning for algorithm portfolios   
2                          Modular deep learning model   
3                    Deep learning processing of video   
4    System and method for deep learning and wirele...   
..                                                 ...   
195  OBJECT CLASSIFICATION WITH CONSTRAINED MULTIPL...   
196  Pre-processing input data with outlier values ...   
197  Large scale semi-supervised linear support vec...   
198  Detection of Textural Defects Using a One Clas...   
199  Method and System for Analysis of Flow Cytomet...   

                                              Abstract  \
0    A method can include selecting a type of geoph...   
1    Automated feature construction for algorithm p...   
2    The technology described herein uses a modular...   
3    A method and system for processing multiple fr...   
4    A neural network is trained using deep reinfor...   
..                                                 ...   
195  This disclosure provides method and systems of...   
196  A system and method for preprocessing input da...   
197  A computerized system and method for large sca...   
198  Method for detecting textural defects in an im...   
199  An automated method and system are provided fo...   

                                           First Claim                  Target  
0    1. A method comprising:\nselecting a type of g...           Deep learning  
1    1. A computer-implemented method of automated ...           Deep learning  
2    1. An automatic speech recognition (ASR) syste...           Deep learning  
3    1. A method comprising:\nperforming a first pr...           Deep learning  
4    1. A method comprising:\ninitializing a neural...           Deep learning  
..                                                 ...                     ...  
195  1. A computer implemented method of classifyin...  Support vector machine  
196  1. A data preprocessor for preprocessing input...  Support vector machine  
197  1. A computerized method for semi-supervised l...  Support vector machine  
198  1. A method for detecting textural defects in ...  Support vector machine  
199  1. A method for analysis and classification of...  Support vector machine  

[200 rows x 4 columns]

In [3]:
#Checking the dimensions of the data frame
d.shape

(200, 4)

In [4]:
d.Target.value_counts()

Deep learning             50
Machine learning          50
Support vector machine    50
Neural network            50
Name: Target, dtype: int64

In [5]:
#Checking for missing values, and dispalying only those columns with missing values
d.isnull().sum()

Title          0
Abstract       0
First Claim    0
Target         0
dtype: int64

In [6]:
# Reassuring all entries are Non-Null and checking data types of all columns
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Title        200 non-null    object
 1   Abstract     200 non-null    object
 2   First Claim  200 non-null    object
 3   Target       200 non-null    object
dtypes: object(4)
memory usage: 6.4+ KB


In [7]:
# Since '1.', 'A', 'An', 'The' are repeating words that doesnt hold any significance to the prediction of Target classification removinf those before embedding
d['First Claim'] = d['First Claim'].str.replace("1. An ", "")
d['First Claim'] = d['First Claim'].str.replace("1. A ", "")
d['Abstract'] = d['Abstract'].str.replace("An ", "")
d['Abstract'] = d['Abstract'].str.replace("A ", "")
d['Abstract'] = d['Abstract'].str.replace("The ", "")
d

Title  \
0                            Geophysical deep learning   
1               Deep learning for algorithm portfolios   
2                          Modular deep learning model   
3                    Deep learning processing of video   
4    System and method for deep learning and wirele...   
..                                                 ...   
195  OBJECT CLASSIFICATION WITH CONSTRAINED MULTIPL...   
196  Pre-processing input data with outlier values ...   
197  Large scale semi-supervised linear support vec...   
198  Detection of Textural Defects Using a One Clas...   
199  Method and System for Analysis of Flow Cytomet...   

                                              Abstract  \
0    method can include selecting a type of geophys...   
1    Automated feature construction for algorithm p...   
2    technology described herein uses a modular mod...   
3    method and system for processing multiple fram...   
4    neural network is trained using deep reinforce...   
..                                                 ...   
195  This disclosure provides method and systems of...   
196  system and method for preprocessing input data...   
197  computerized system and method for large scale...   
198  Method for detecting textural defects in an im...   
199  automated method and system are provided for r...   

                                           First Claim                  Target  
0    method comprising:\nselecting a type of geophy...           Deep learning  
1    computer-implemented method of automated featu...           Deep learning  
2    automatic speech recognition (ASR) system for ...           Deep learning  
3    method comprising:\nperforming a first process...           Deep learning  
4    method comprising:\ninitializing a neural netw...           Deep learning  
..                                                 ...                     ...  
195  computer implemented method of classifying a d...  Support vector machine  
196  data preprocessor for preprocessing input data...  Support vector machine  
197  computerized method for semi-supervised learni...  Support vector machine  
198  method for detecting textural defects in an im...  Support vector machine  
199  method for analysis and classification of flow...  Support vector machine  

[200 rows x 4 columns]

In [8]:
# Making all characters lowercase
d['First Claim'] = d['First Claim'].str.lower()
d['Abstract'] = d['Abstract'].str.lower()
d['Title'] = d['Title'].str.lower()
d

Title  \
0                            geophysical deep learning   
1               deep learning for algorithm portfolios   
2                          modular deep learning model   
3                    deep learning processing of video   
4    system and method for deep learning and wirele...   
..                                                 ...   
195  object classification with constrained multipl...   
196  pre-processing input data with outlier values ...   
197  large scale semi-supervised linear support vec...   
198  detection of textural defects using a one clas...   
199  method and system for analysis of flow cytomet...   

                                              Abstract  \
0    method can include selecting a type of geophys...   
1    automated feature construction for algorithm p...   
2    technology described herein uses a modular mod...   
3    method and system for processing multiple fram...   
4    neural network is trained using deep reinforce...   
..                                                 ...   
195  this disclosure provides method and systems of...   
196  system and method for preprocessing input data...   
197  computerized system and method for large scale...   
198  method for detecting textural defects in an im...   
199  automated method and system are provided for r...   

                                           First Claim                  Target  
0    method comprising:\nselecting a type of geophy...           Deep learning  
1    computer-implemented method of automated featu...           Deep learning  
2    automatic speech recognition (asr) system for ...           Deep learning  
3    method comprising:\nperforming a first process...           Deep learning  
4    method comprising:\ninitializing a neural netw...           Deep learning  
..                                                 ...                     ...  
195  computer implemented method of classifying a d...  Support vector machine  
196  data preprocessor for preprocessing input data...  Support vector machine  
197  computerized method for semi-supervised learni...  Support vector machine  
198  method for detecting textural defects in an im...  Support vector machine  
199  method for analysis and classification of flow...  Support vector machine  

[200 rows x 4 columns]

In [9]:
# Removing non-alpha numeric charecters
d['First Claim'] = d['First Claim'].str.replace('[^a-z]', ' ', regex=True).str.strip()
d['Abstract'] = d['Abstract'].str.replace('[^a-z]', ' ', regex=True).str.strip()
d['Title'] = d['Title'].str.replace('[^a-z]', ' ', regex=True).str.strip()
d

Title  \
0                            geophysical deep learning   
1               deep learning for algorithm portfolios   
2                          modular deep learning model   
3                    deep learning processing of video   
4    system and method for deep learning and wirele...   
..                                                 ...   
195  object classification with constrained multipl...   
196  pre processing input data with outlier values ...   
197  large scale semi supervised linear support vec...   
198  detection of textural defects using a one clas...   
199  method and system for analysis of flow cytomet...   

                                              Abstract  \
0    method can include selecting a type of geophys...   
1    automated feature construction for algorithm p...   
2    technology described herein uses a modular mod...   
3    method and system for processing multiple fram...   
4    neural network is trained using deep reinforce...   
..                                                 ...   
195  this disclosure provides method and systems of...   
196  system and method for preprocessing input data...   
197  computerized system and method for large scale...   
198  method for detecting textural defects in an im...   
199  automated method and system are provided for r...   

                                           First Claim                  Target  
0    method comprising  selecting a type of geophys...           Deep learning  
1    computer implemented method of automated featu...           Deep learning  
2    automatic speech recognition  asr  system for ...           Deep learning  
3    method comprising  performing a first processi...           Deep learning  
4    method comprising  initializing a neural netwo...           Deep learning  
..                                                 ...                     ...  
195  computer implemented method of classifying a d...  Support vector machine  
196  data preprocessor for preprocessing input data...  Support vector machine  
197  computerized method for semi supervised learni...  Support vector machine  
198  method for detecting textural defects in an im...  Support vector machine  
199  method for analysis and classification of flow...  Support vector machine  

[200 rows x 4 columns]

In [10]:
# Merging Title, Abstract and First Claim columns together to get one text column

d['Text'] = d[d.columns[0:3]].apply(lambda x: ' '.join(x.dropna().astype(str)), axis=1)
d['Text'].iloc[0]

'geophysical deep learning method can include selecting a type of geophysical data  selecting a type of algorithm  generating synthetic geophysical data based at least in part on the algorithm  training a deep learning framework based at least in part on the synthetic geophysical data to generate a trained deep learning framework  receiving acquired geophysical data for a geologic environment  implementing the trained deep learning framework to generate interpretation results for the acquired geophysical data  and outputting the interpretation results method comprising  selecting a type of geophysical data  selecting a type of algorithm  generating synthetic geophysical data of the selected type of geophysical data based at least in part on the algorithm  training a deep learning classifier framework based at least in part on the synthetic geophysical data to generate a trained deep learning classifier framework  receiving acquired geophysical data for a geologic environment  implement

In [11]:
# Dropping Title, Abstract and First Claim columns
d = d.drop(d.columns[[0,1,2]], axis=1)
d

Target                                               Text
0             Deep learning  geophysical deep learning method can include s...
1             Deep learning  deep learning for algorithm portfolios automat...
2             Deep learning  modular deep learning model technology describ...
3             Deep learning  deep learning processing of video method and s...
4             Deep learning  system and method for deep learning and wirele...
..                      ...                                                ...
195  Support vector machine  object classification with constrained multipl...
196  Support vector machine  pre processing input data with outlier values ...
197  Support vector machine  large scale semi supervised linear support vec...
198  Support vector machine  detection of textural defects using a one clas...
199  Support vector machine  method and system for analysis of flow cytomet...

[200 rows x 2 columns]

In [12]:
count_vectorizer = CountVectorizer()

In [13]:
wm = count_vectorizer.fit_transform(d.Text)

doc_names = ['Doc{:d}'.format(idx) for idx, _ in enumerate(wm)]
feat_names = count_vectorizer.get_feature_names()


Title_df = pd.DataFrame(data=wm.toarray(), index=doc_names,columns=feat_names)
Title_df

able  abnormal  abnormality  about  above  absence  absent  absolute  \
Doc0       0         0            0      0      0        0       0         0   
Doc1       0         0            0      0      0        0       0         0   
Doc2       0         0            0      0      0        0       0         0   
Doc3       0         0            0      0      0        0       0         0   
Doc4       0         0            0      0      0        0       0         0   
...      ...       ...          ...    ...    ...      ...     ...       ...   
Doc195     0         0            0      0      0        0       0         0   
Doc196     0         0            0      0      0        0       0         0   
Doc197     0         0            0      0      0        0       0         0   
Doc198     0         0            0      0      0        0       0         0   
Doc199     0         0            0      0      0        0       0         0   

        absorption  abstract  accelerate  accelerated  acceleration  \
Doc0             0         0           0            0             0   
Doc1             0         0           0            0             0   
Doc2             0         0           0            0             0   
Doc3             0         0           0            0             0   
Doc4             0         0           0            0             0   
...            ...       ...         ...          ...           ...   
Doc195           0         0           0            0             0   
Doc196           0         0           0            0             0   
Doc197           0         0           0            0             0   
Doc198           0         0           0            0             0   
Doc199           0         0           0            0             0   

        accelerator  accelerators  accent  accept  acceptable  accepting  \
Doc0              0             0       0       0           0          0   
Doc1              0             0       0       0           0          0   
Doc2              0             0       1       0           0          0   
Doc3              0             0       0       0           0          0   
Doc4              0             0       0       0           1          0   
...             ...           ...     ...     ...         ...        ...   
Doc195            0             0       0       0           0          0   
Doc196            0             0       0       0           0          0   
Doc197            0             0       0       0           0          0   
Doc198            0             0       0       0           0          0   
Doc199            0             0       0       0           0          0   

        accepts  access  accessed  accessible  accessing  accomplish  \
Doc0          0       0         0           0          0           0   
Doc1          0       0         0           0          0           0   
Doc2          0       0         0           0          0           0   
Doc3          0       0         0           0          0           0   
Doc4          0       0         0           0          0           0   
...         ...     ...       ...         ...        ...         ...   
Doc195        0       0         0           0          0           0   
Doc196        0       0         0           0          0           0   
Doc197        0       0         0           0          0           0   
Doc198        0       0         0           0          0           0   
Doc199        0       0         0           0          0           0   

        accomplished  accordance  according  accordingly  account  accumulate  \
Doc0               0           0          0            0        0           0   
Doc1               0           0          0            0        0           0   
Doc2               0           0          0            0        0           0   
Doc3               0           0          0            0        0           0   
Doc4       

<h3> Train-Test Data Creation </h3>

Need to split the dataset into Train and Test datasets using 80/20 split in order to train and test ML models. To split the whole dataset into two, the train_test_split functionaluty from sklearn library can be used, wherein the Train data will be used to build the model and test data to evaluate the performance of the model.

In [14]:
x = d.Text #independent variable
y = d.Target #dependent variable
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1 ,stratify= y)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(160,) (160,)
(40,) (40,)


In [15]:
# tf-idf embedding
tfidf = TfidfVectorizer() 

tfidf_train_vectors = tfidf.fit_transform(x_train)

tfidf_test_vectors = tfidf.transform(x_test)

<h3> Bulding Classification Models </h3>

Using different supervised ML classification algorithoms on training data set classification models are build and the performance is validated using test data set.

<h4> Linear SVC </h4>

The Linear Support Vector Classifier (L SVC) method applies a linear kernel function to perform classification and it performs well with a large number of samples. If we compare it with the SVC model, the Linear SVC has additional parameters such as penalty normalization which applies 'L1' or 'L2' and loss function. The kernel method can not be changed in linear SVC, because it is based on the kernel linear method. 

In [16]:
#Building Model
svc = LinearSVC()
svc.fit(tfidf_train_vectors, y_train)

y_pred_train = svc.predict(tfidf_train_vectors)
y_pred = svc.predict(tfidf_test_vectors)

error_train = zero_one_loss(y_train, y_pred_train)
error = zero_one_loss(y_test, y_pred)

train_svc = confusion_matrix(y_train, y_pred_train)
results_svc = confusion_matrix(y_test, y_pred)

print("Confusion Matrix of Train dataset: \n", train_svc)
print("\n Accuracy on train dataset:", accuracy_score(y_train, y_pred_train))
print("\n Error in Train dataset: ", error_train)
print("\n Model Performance in Train dataset: \n",classification_report(y_train, y_pred_train))

print("\n Confusion Matrix of Test dataset: \n", results_svc)
print("\n Accuracy on Test dataset: ", accuracy_score(y_pred, y_test))
print("\n Error in Test dataset: ", error)
print("\n Model Performance in Test dataset: \n",classification_report(y_test, y_pred))

Confusion Matrix of Train dataset: 
 [[40  0  0  0]
 [ 0 40  0  0]
 [ 0  0 40  0]
 [ 0  0  0 40]]

 Accuracy on train dataset: 1.0

 Error in Train dataset:  0.0

 Model Performance in Train dataset: 
                         precision    recall  f1-score   support

         Deep learning       1.00      1.00      1.00        40
      Machine learning       1.00      1.00      1.00        40
        Neural network       1.00      1.00      1.00        40
Support vector machine       1.00      1.00      1.00        40

              accuracy                           1.00       160
             macro avg       1.00      1.00      1.00       160
          weighted avg       1.00      1.00      1.00       160


 Confusion Matrix of Test dataset: 
 [[6 2 2 0]
 [1 8 0 1]
 [0 1 9 0]
 [1 0 0 9]]

 Accuracy on Test dataset:  0.8

 Error in Test dataset:  0.19999999999999996

 Model Performance in Test dataset: 
                         precision    recall  f1-score   support

         Deep lea

<h4> MLP </h4>

Multiple Linear Regression is a commonly used artificial neural network built out of artificial neurons. An artificial neuron simple computational unit that weigh input signals and produce an output signal utilizing an activation function.An MLP learns to model the correlation of input-output pairs by changing the connection weights after each packet of data is processed and compares the amount of error in the output to the expected result.This supervised learning is carried out through backpropagation which is a generalization of the least mean squares algorithm in the linear perceptron, and trains by adjusting the parameters, weights and biases of the model to minimize the error.

In [17]:
mlp = MLPClassifier()
mlp.fit(tfidf_train_vectors, y_train)

y_pred_train = mlp.predict(tfidf_train_vectors)
y_pred = mlp.predict(tfidf_test_vectors)

error_train = zero_one_loss(y_train, y_pred_train)
error = zero_one_loss(y_test, y_pred)

train_mlp = confusion_matrix(y_train, y_pred_train)
results_mlp = confusion_matrix(y_test, y_pred)

print("Confusion Matrix of Train dataset: \n", train_mlp)
print("\n Accuracy on train dataset:", accuracy_score(y_train, y_pred_train))
print("\n Error in Train dataset: ", error)
print("\n Model Performance in Train dataset: \n",classification_report(y_train, y_pred_train))

print("\n Confusion Matrix of Test dataset: \n", results_mlp)
print("\n Accuracy on Test dataset: ", accuracy_score(y_pred, y_test))
print("\n Error in Test dataset: ", error)
print("\n Model Performance in Test dataset: \n",classification_report(y_test, y_pred))

Confusion Matrix of Train dataset: 
 [[40  0  0  0]
 [ 0 40  0  0]
 [ 0  0 40  0]
 [ 0  0  0 40]]

 Accuracy on train dataset: 1.0

 Error in Train dataset:  0.275

 Model Performance in Train dataset: 
                         precision    recall  f1-score   support

         Deep learning       1.00      1.00      1.00        40
      Machine learning       1.00      1.00      1.00        40
        Neural network       1.00      1.00      1.00        40
Support vector machine       1.00      1.00      1.00        40

              accuracy                           1.00       160
             macro avg       1.00      1.00      1.00       160
          weighted avg       1.00      1.00      1.00       160


 Confusion Matrix of Test dataset: 
 [[7 2 1 0]
 [3 6 0 1]
 [0 1 8 1]
 [1 1 0 8]]

 Accuracy on Test dataset:  0.725

 Error in Test dataset:  0.275

 Model Performance in Test dataset: 
                         precision    recall  f1-score   support

         Deep learning     

<h4> LR </h4>

Logistic Regression classifier is a predictive analysis algorithm based on the concept of probability. It can only be used when the target variables are discrete/categorical. When using logistic regression, a threshold must be specified based on which the algorithm can decide whether to put a value into one class or the other.Logistic Regression is actually a Linear Regression model with more complex cost function, known as the ‘Sigmoid function’.The objective of the algorithm is to minimize the cost function so that accuracy will be maximized. To minimize the cost function, a gradient descent function is run on each parameter.

In [20]:
lr = LogisticRegression()
lr.fit(tfidf_train_vectors, y_train)
y_pred_train = lr.predict(tfidf_train_vectors)
y_pred = lr.predict(tfidf_test_vectors)

error_train = zero_one_loss(y_train, y_pred_train)
error = zero_one_loss(y_test, y_pred)

train_lr = confusion_matrix(y_train, y_pred_train)
results_lr = confusion_matrix(y_test, y_pred)

print("Confusion Matrix of Train dataset: \n", train_lr)
print("\n Accuracy on train dataset:", accuracy_score(y_train, y_pred_train))
print("\n Error in Train dataset: ", error_train)
print("\n Model Performance in Train dataset: \n",classification_report(y_train, y_pred_train))

print("\n Confusion Matrix of Test dataset: \n", results_lr)
print("\n Accuracy on Test dataset: ", accuracy_score(y_pred, y_test))
print("\n Error in Test dataset: ", error)
print("\n Model Performance in Test dataset: \n",classification_report(y_test, y_pred))

Confusion Matrix of Train dataset: 
 [[40  0  0  0]
 [ 0 40  0  0]
 [ 0  0 40  0]
 [ 0  0  0 40]]

 Accuracy on train dataset: 1.0

 Error in Train dataset:  0.0

 Model Performance in Train dataset: 
                         precision    recall  f1-score   support

         Deep learning       1.00      1.00      1.00        40
      Machine learning       1.00      1.00      1.00        40
        Neural network       1.00      1.00      1.00        40
Support vector machine       1.00      1.00      1.00        40

              accuracy                           1.00       160
             macro avg       1.00      1.00      1.00       160
          weighted avg       1.00      1.00      1.00       160


 Confusion Matrix of Test dataset: 
 [[7 2 1 0]
 [1 8 0 1]
 [0 1 9 0]
 [1 0 0 9]]

 Accuracy on Test dataset:  0.825

 Error in Test dataset:  0.17500000000000004

 Model Performance in Test dataset: 
                         precision    recall  f1-score   support

         Deep l

<h4> RF </h4>

Random Forest is a popular machine learning algorithm that belongs to the supervised learning technique. It can be used for both Classification and Regression problems in ML. It is based on the concept of ensemble learning, which is a process of combining multiple classifiers to solve a complex problem and to improve the performance of the model. As the name suggests, "Random Forest is a classifier that contains a number of decision trees on various subsets of the given dataset and takes the average to improve the predictive accuracy of that dataset." Instead of relying on one decision tree, the random forest takes the prediction from each tree and based on the majority votes of predictions, and it predicts the final output. The greater number of trees in the forest leads to higher accuracy and prevents the problem of overfitting.

In [19]:
#Building Model
rf = RandomForestClassifier()
rf.fit(tfidf_train_vectors, y_train)

y_pred_train = rf.predict(tfidf_train_vectors)
y_pred = rf.predict(tfidf_test_vectors)

error_train = zero_one_loss(y_train, y_pred_train)
error = zero_one_loss(y_test, y_pred)

train_rf = confusion_matrix(y_train, y_pred_train)
results_rf = confusion_matrix(y_test, y_pred)

print("Confusion Matrix of Train dataset: \n", train_rf)
print("\n Accuracy on train dataset:", accuracy_score(y_train, y_pred_train))
print("\n Error in Train dataset: ", error_train)
print("\n Model Performance in Train dataset: \n",classification_report(y_train, y_pred_train))

print("\n Confusion Matrix of Test dataset: \n", results_rf)
print("\n Accuracy on Test dataset: ", accuracy_score(y_pred, y_test))
print("\n Error in Test dataset: ", error)
print("\n Model Performance in Test dataset: \n",classification_report(y_test, y_pred))

Confusion Matrix of Train dataset: 
 [[40  0  0  0]
 [ 0 40  0  0]
 [ 0  0 40  0]
 [ 0  0  0 40]]

 Accuracy on train dataset: 1.0

 Error in Train dataset:  0.0

 Model Performance in Train dataset: 
                         precision    recall  f1-score   support

         Deep learning       1.00      1.00      1.00        40
      Machine learning       1.00      1.00      1.00        40
        Neural network       1.00      1.00      1.00        40
Support vector machine       1.00      1.00      1.00        40

              accuracy                           1.00       160
             macro avg       1.00      1.00      1.00       160
          weighted avg       1.00      1.00      1.00       160


 Confusion Matrix of Test dataset: 
 [[10  0  0  0]
 [ 1  8  0  1]
 [ 1  0  9  0]
 [ 0  0  0 10]]

 Accuracy on Test dataset:  0.925

 Error in Test dataset:  0.07499999999999996

 Model Performance in Test dataset: 
                         precision    recall  f1-score   support
